#BLEU doc
python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEUdoc/seed_1/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 1 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_1/EPOCH_acc_52.55_ppl_16.16_e4.pt -gpuid 0 -doc_level_reward True -doc_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEUdoc/seed_2/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 2 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_2/EPOCH_acc_52.08_ppl_16.69_e8.pt -gpuid 0 -doc_level_reward True -doc_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEUdoc/seed_3/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 3 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_3/EPOCH_acc_52.46_ppl_15.93_e5.pt -gpuid 0 -doc_level_reward True -doc_bleu True

#LC COH doc
python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_LC_COH_doc/seed_1/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 1 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_1/EPOCH_acc_52.55_ppl_16.16_e4.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_LC_COH_doc/seed_2/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 2 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_2/EPOCH_acc_52.08_ppl_16.69_e8.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_LC_COH_doc/seed_3/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 3 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_3/EPOCH_acc_52.46_ppl_15.93_e5.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True


#LC COH doc and BLEUsen
python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_LC_COH_doc_and_BLEUsen/seed_1/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 1 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_1/EPOCH_acc_52.55_ppl_16.16_e4.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -sen_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_LC_COH_doc_and_BLEUsen/seed_2/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 2 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_2/EPOCH_acc_52.08_ppl_16.69_e8.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -sen_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_LC_COH_doc_and_BLEUsen/seed_3/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 3 -train_validate True -RISK_ratio 1.0 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_3/EPOCH_acc_52.46_ppl_15.93_e5.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -sen_bleu True


#LC COH doc and BLEUdoc RISK 0.5
python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEU_LC_coher_RISK_0.5/seed_1/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 1 -train_validate True -RISK_ratio 0.5 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_1/EPOCH_acc_52.55_ppl_16.16_e4.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -doc_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEU_LC_coher_RISK_0.5/seed_2/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 2 -train_validate True -RISK_ratio 0.5 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_2/EPOCH_acc_52.08_ppl_16.69_e8.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -doc_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEU_LC_coher_RISK_0.5/seed_3/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 3 -train_validate True -RISK_ratio 0.5 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_3/EPOCH_acc_52.46_ppl_15.93_e5.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -doc_bleu True

#LC COH doc and BLEUdoc RISK 0.8
python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEU_LC_coher_RISK_0.8/seed_1/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 1 -train_validate True -RISK_ratio 0.8 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_1/EPOCH_acc_52.55_ppl_16.16_e4.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -doc_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEU_LC_coher_RISK_0.8/seed_2/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 2 -train_validate True -RISK_ratio 0.8 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_2/EPOCH_acc_52.08_ppl_16.69_e8.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -doc_bleu True

python train.py -data ../cs-en/IWSLT16.TED_CS_EN -save_model cs-en_models/HAN_join_plus_RL_BLEU_LC_coher_RISK_0.8/seed_3/EPOCH -encoder_type transformer -decoder_type transformer -enc_layers 6 -dec_layers 6 -label_smoothing 0.1 -src_word_vec_size 512 -tgt_word_vec_size 512 -rnn_size 512 -position_encoding -dropout 0.1 -batch_size 15 -start_decay_at 2 -report_every 500 -epochs 2 -max_generator_batches 32 -accum_count 4 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 0.2 -max_grad_norm 0 -param_init 0 -param_init_glorot -train_part all -context_type HAN_join -context_size 3 -seed 3 -train_validate True -RISK_ratio 0.8 -beam_size 2 -n_best 2 -train_from cs-en_models/HAN_join_newCodeAGAIN/seed_3/EPOCH_acc_52.46_ppl_15.93_e5.pt -gpuid 0 -doc_level_reward True -doc_LC_COH True -doc_bleu True


